<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Jerwell Escusa - Regression Analysis Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../icon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../helsinki_dap2324/project_regression-analysis.html">University of Helsinki: Data Analysis with Python</a></li><li class="breadcrumb-item"><a href="../helsinki_dap2324/project_regression-analysis.html">Regression Analysis Project</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Jerwell Escusa</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About Me</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">CS50 SQL: Human Resources Database</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cs50_sql/design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Database Design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cs50_sql/schema.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Database Schema</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cs50_sql/queries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Database Queries</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">University of Helsinki: Data Analysis with Python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../helsinki_dap2324/project_regression-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Regression Analysis Project</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link active" data-scroll-target="#prerequisites">Prerequisites</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a>
  <ul class="collapse">
  <li><a href="#even-more-accurate-model" id="toc-even-more-accurate-model" class="nav-link" data-scroll-target="#even-more-accurate-model">Even more accurate model</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic regression</a>
  <ul class="collapse">
  <li><a href="#predicting-coronary-heart-disease" id="toc-predicting-coronary-heart-disease" class="nav-link" data-scroll-target="#predicting-coronary-heart-disease">Predicting coronary heart disease</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../helsinki_dap2324/project_regression-analysis.html">University of Helsinki: Data Analysis with Python</a></li><li class="breadcrumb-item"><a href="../helsinki_dap2324/project_regression-analysis.html">Regression Analysis Project</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Regression Analysis Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>My code inputs in each code block are preceded by <code># Put your solution here!</code> line, and the textual inputs are found inside solid <span style="color: #886EB1;"><strong>violet</strong></span> borders.</p>
</div>
</div>
<section id="prerequisites" class="level2">
<h2 class="anchored" data-anchor-id="prerequisites">Prerequisites</h2>
<p>Import all the modules you will need in this notebook here:</p>
<div id="600bf600" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 0</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plots a line given an intercept and a slope</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.regressionplots <span class="im">import</span> abline_plot</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<p>We continue analysing the <code>fram</code> heart disease data.</p>
<p>First load the data, use the name <code>fram</code> for the DataFrame variable. Make sure that in the data you loaded the column and row headers are in place. Checkout the summary of the variables using the <code>describe</code> method.</p>
<div id="44f0e7d6" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_path(filename):</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="im">import</span> sys</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="im">import</span> os</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    prog_name <span class="op">=</span> sys.argv[<span class="dv">0</span>]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> os.path.basename(prog_name) <span class="op">==</span> <span class="st">"__main__.py"</span>:   <span class="co"># Running under TMC</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> os.path.join(os.path.dirname(prog_name), <span class="st">".."</span>, <span class="st">"src"</span>, filename)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> filename</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>fram <span class="op">=</span> pd.read_csv(get_path(<span class="st">"fram.txt"</span>), sep<span class="op">=</span><span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>fram.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">AGE</th>
<th data-quarto-table-cell-role="th">FRW</th>
<th data-quarto-table-cell-role="th">SBP</th>
<th data-quarto-table-cell-role="th">SBP10</th>
<th data-quarto-table-cell-role="th">DBP</th>
<th data-quarto-table-cell-role="th">CHOL</th>
<th data-quarto-table-cell-role="th">CIG</th>
<th data-quarto-table-cell-role="th">CHD</th>
<th data-quarto-table-cell-role="th">DEATH</th>
<th data-quarto-table-cell-role="th">YRS_DTH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>1394.000000</td>
<td>1394.000000</td>
<td>1394.000000</td>
<td>1394.000000</td>
<td>767.000000</td>
<td>1394.000000</td>
<td>1394.000000</td>
<td>1394.000000</td>
<td>1394.000000</td>
<td>1394.000000</td>
<td>1394.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>4737.184362</td>
<td>52.431133</td>
<td>105.365136</td>
<td>148.086083</td>
<td>148.040417</td>
<td>90.135581</td>
<td>234.644907</td>
<td>8.029412</td>
<td>1.187948</td>
<td>1.700861</td>
<td>16.219512</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>1073.406896</td>
<td>4.781507</td>
<td>17.752489</td>
<td>28.022062</td>
<td>25.706664</td>
<td>14.226235</td>
<td>46.303822</td>
<td>11.584138</td>
<td>2.615976</td>
<td>3.203132</td>
<td>3.921413</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1070.000000</td>
<td>45.000000</td>
<td>52.000000</td>
<td>90.000000</td>
<td>94.000000</td>
<td>50.000000</td>
<td>96.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>3890.250000</td>
<td>48.000000</td>
<td>94.000000</td>
<td>130.000000</td>
<td>130.000000</td>
<td>80.000000</td>
<td>200.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>18.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>4821.000000</td>
<td>52.000000</td>
<td>103.000000</td>
<td>142.000000</td>
<td>145.000000</td>
<td>90.000000</td>
<td>230.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>18.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>5641.750000</td>
<td>56.000000</td>
<td>114.000000</td>
<td>160.000000</td>
<td>160.000000</td>
<td>98.000000</td>
<td>264.000000</td>
<td>20.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>18.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>6442.000000</td>
<td>62.000000</td>
<td>222.000000</td>
<td>300.000000</td>
<td>264.000000</td>
<td>160.000000</td>
<td>430.000000</td>
<td>60.000000</td>
<td>10.000000</td>
<td>10.000000</td>
<td>18.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Create function <code>rescale</code> that takes a Series as parameter. It should center the data and normalize it by dividing by 2 <span class="math inline">\(\sigma\)</span>, where <span class="math inline">\(\sigma\)</span> is the standard deviation. Return the rescaled Series.</p>
<div id="7a854d48" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 2</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rescale(s):</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    center <span class="op">=</span> s.mean()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    normal <span class="op">=</span> <span class="dv">2</span><span class="op">*</span>s.std()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (s<span class="op">-</span>center)<span class="op">/</span>normal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Add to the DataFrame the scaled versions of all the continuous variables (with function <code>rescale</code>). Add small letter <code>s</code> in front of the original variable name to get the name of the scaled variable. For instance, <code>AGE</code> -&gt; <code>sAGE</code>.</p>
<div id="8a520d53" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 3</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>new <span class="op">=</span> [<span class="st">"s"</span><span class="op">+</span>x <span class="cf">for</span> x <span class="kw">in</span> fram.columns[<span class="dv">2</span>:<span class="dv">9</span>].drop(<span class="st">"SBP10"</span>)]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>fram[new] <span class="op">=</span> rescale(fram.loc[:, <span class="st">"AGE"</span>:<span class="st">"CIG"</span>].drop(<span class="st">"SBP10"</span>, axis<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># fram.describe() # The rescaled variables have mean 0 and std 0.5</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># The rescaling makes the beta cofficients of continuous variables comparable to the coefficients of binary variables.</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Gelman, A. (2008). Scaling regression inputs by dividing by two standard deviations. Statistics in Medicine, </span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 27(15), 2865–2873. https://doi.org/10.1002/sim.3107</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Form a model that predicts systolic blood pressure using weight, gender, and cholesterol level as explanatory variables. Store the fitted model in variable named <code>fit</code>.</p>
<div id="dca7fe8c" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 4</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.ols(<span class="st">'SBP ~ SEX + sFRW + sCHOL'</span>, data<span class="op">=</span>fram).fit()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    SBP   R-squared:                       0.125
Model:                            OLS   Adj. R-squared:                  0.123
Method:                 Least Squares   F-statistic:                     66.37
Date:                Thu, 20 Jun 2024   Prob (F-statistic):           4.13e-40
Time:                        23:33:55   Log-Likelihood:                -6530.4
No. Observations:                1394   AIC:                         1.307e+04
Df Residuals:                    1390   BIC:                         1.309e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P&gt;|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     150.0199      0.985    152.336      0.000     148.088     151.952
SEX[T.male]    -4.0659      1.451     -2.803      0.005      -6.912      -1.220
sFRW           17.7205      1.426     12.431      0.000      14.924      20.517
sCHOL           4.9169      1.431      3.436      0.001       2.110       7.724
==============================================================================
Omnibus:                      327.612   Durbin-Watson:                   1.774
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              843.676
Skew:                           1.237   Prob(JB):                    6.28e-184
Kurtosis:                       5.899   Cond. No.                         2.79
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Add the variable AGE to the model and inspect the estimates of the coefficients using the <code>summary</code> method of the fitted model. Again use the name <code>fit</code> for the fitted model. (From now on assume that we always use the name <code>fit</code> for the variable of the fitted model.)</p>
<div id="81db349e" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 5</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.ols(<span class="st">'SBP ~ SEX + sFRW + sCHOL + sAGE'</span>, data<span class="op">=</span>fram).fit()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    SBP   R-squared:                       0.146
Model:                            OLS   Adj. R-squared:                  0.144
Method:                 Least Squares   F-statistic:                     59.39
Date:                Thu, 20 Jun 2024   Prob (F-statistic):           2.44e-46
Time:                        23:33:55   Log-Likelihood:                -6513.6
No. Observations:                1394   AIC:                         1.304e+04
Df Residuals:                    1389   BIC:                         1.306e+04
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P&gt;|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     150.1695      0.974    154.221      0.000     148.259     152.080
SEX[T.male]    -4.3805      1.435     -3.053      0.002      -7.195      -1.566
sFRW           16.9771      1.415     11.999      0.000      14.202      19.753
sCHOL           4.2696      1.419      3.009      0.003       1.486       7.053
sAGE            8.1332      1.400      5.810      0.000       5.387      10.879
==============================================================================
Omnibus:                      321.087   Durbin-Watson:                   1.807
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              840.955
Skew:                           1.206   Prob(JB):                    2.45e-183
Kurtosis:                       5.944   Cond. No.                         2.82
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>How much does the inclusion of age increase the explanatory power of the model? Which variables explain the variance of the target variable most?</p>
<hr>
<div class="answers">
<p>For the first question, first, it’s important to define R-squared. The R-squared gives an estimate of how much of the variation in y (dependent variable) is explained by the x’s (explanatory variables). A value of 1.00 means all the variation in y is explained by the x’s. The model including <code>sAGE</code>and its interactions have higher R-squared (higher is better) than the model without these variables, a difference of 0.021. The same is true with the adjusted R-squared, which penalizes the addition of more explanatory variables. It’s important to remember not to put too much weight on the R-squared in terms of model evaluation. For the next question, the outputs produced so far from the codes cannot answer this question. The package <a href="https://dominance-analysis.github.io/dominance-analysis/"><code>dominance-analysis</code></a> may be useful for answering this question. Now, what the outputs could show are the differences in the magnitude of their effect on the dependent variable, which are now easily compared due to the rescaling earlier. Each beta coefficient now corresponds to a change of two standard deviations (1 unit change in a variable with 0.5 standard deviation). Given this, comparing the absolute value of their beta coefficients, this is the order of explanatory variables: <code>sFRW</code>, <code>sAGE</code>, <code>SEX</code>, <code>sCHOL</code>. In this case, however, the results from my implementation of the <code>dominance-analysis</code> package reveal a similar story.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dominance_analysis <span class="im">import</span> Dominance_Datasets</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> dominance_analysis <span class="im">import</span> Dominance</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>dom_data <span class="op">=</span> fram[[<span class="st">"SBP"</span>, <span class="st">"SEX"</span>, <span class="st">"sFRW"</span>, <span class="st">"sCHOL"</span>, <span class="st">"sAGE"</span>]]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>dom_data.SEX <span class="op">=</span> (dom_data.SEX <span class="op">==</span> <span class="st">"male"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>dom_data.SEX <span class="op">=</span> dom_data.SEX.astype(<span class="st">"int"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>dominance_regression<span class="op">=</span>Dominance(data<span class="op">=</span>dom_data,target<span class="op">=</span><span class="st">'SBP'</span>,objective<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>incr_variable_rsquare<span class="op">=</span>dominance_regression.incremental_rsquare()</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>dominance_regression.dominance_stats()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>percentage_relative_importance <span class="op">=</span> {<span class="st">'sFRW'</span>: <span class="fl">67.71633624572831</span>, <span class="st">'sAGE'</span>: <span class="fl">17.724686667202082</span>, </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="st">'SEX'</span>: <span class="fl">8.476548868422698</span>, <span class="st">'sCHOL'</span>: <span class="fl">6.082428218646909</span>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p>Try to add to the model all the interactions with other variables.</p>
<div id="a67d57c3" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 6</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.ols(<span class="st">'SBP ~ SEX + SEX:sFRW + SEX:sCHOL + SEX:sAGE + sFRW + sFRW:sCHOL + sFRW:sAGE + sCHOL + sCHOL:sAGE + sAGE'</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>              data<span class="op">=</span>fram).fit()</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    SBP   R-squared:                       0.151
Model:                            OLS   Adj. R-squared:                  0.144
Method:                 Least Squares   F-statistic:                     24.52
Date:                Thu, 20 Jun 2024   Prob (F-statistic):           4.92e-43
Time:                        23:33:55   Log-Likelihood:                -6509.9
No. Observations:                1394   AIC:                         1.304e+04
Df Residuals:                    1383   BIC:                         1.310e+04
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P&gt;|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept           150.5439      1.001    150.355      0.000     148.580     152.508
SEX[T.male]          -4.7309      1.451     -3.261      0.001      -7.577      -1.885
sFRW                 16.6450      1.723      9.660      0.000      13.265      20.025
SEX[T.male]:sFRW      1.6673      3.088      0.540      0.589      -4.390       7.725
sCHOL                 3.6181      1.878      1.926      0.054      -0.066       7.302
SEX[T.male]:sCHOL     1.0231      2.933      0.349      0.727      -4.730       6.776
sAGE                 10.2189      2.003      5.101      0.000       6.289      14.149
SEX[T.male]:sAGE     -4.2923      2.886     -1.488      0.137      -9.953       1.368
sFRW:sCHOL            4.9729      2.718      1.829      0.068      -0.359      10.305
sFRW:sAGE            -2.0866      2.803     -0.744      0.457      -7.585       3.412
sCHOL:sAGE           -4.7564      3.044     -1.563      0.118     -10.728       1.215
==============================================================================
Omnibus:                      313.112   Durbin-Watson:                   1.798
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              802.290
Skew:                           1.185   Prob(JB):                    6.10e-175
Kurtosis:                       5.863   Cond. No.                         6.02
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Then visualize the model as the function of weight for the youngest (sAGE=-1.0), middle aged (sAGE=0.0), and oldest (sAGE=1.0) women while assuming the background variables to be centered. Remember to consider the changes in the intercept and in the regression coefficient caused by age. Visualize both the data points and the fitted lines.</p>
<div id="ed0e354d" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 7</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining colors based on viridis color map (yellow - violet)</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>viridis <span class="op">=</span> {</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>: <span class="st">"#fde725"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>: <span class="st">"#addc30"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>: <span class="st">"#5ec962"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="dv">3</span>: <span class="st">"#28ae80"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="dv">4</span>: <span class="st">"#21918c"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="dv">5</span>: <span class="st">"#2c728e"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="dv">6</span>: <span class="st">"#3b528b"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="dv">7</span>: <span class="st">"#472d7b"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="dv">8</span>: <span class="st">"#440154"</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> fit.params</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="co"># SEX = "female"</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>fram[fram.SEX<span class="op">==</span><span class="st">"female"</span>].plot.scatter(<span class="st">"sFRW"</span>, <span class="st">"SBP"</span>, c<span class="op">=</span>viridis[<span class="dv">8</span>])</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co">## Youngest, sAGE = -1.0</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>abline_plot(intercept<span class="op">=</span>p.Intercept <span class="op">-</span> p[<span class="st">"sAGE"</span>], slope<span class="op">=</span>p.sFRW <span class="op">-</span> p[<span class="st">"sFRW:sAGE"</span>],</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>plt.gca(), color<span class="op">=</span>viridis[<span class="dv">0</span>], label<span class="op">=</span><span class="st">"youngest"</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="co">## Middle-aged, sAGE = 0.0</span></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>abline_plot(intercept<span class="op">=</span>p.Intercept, slope<span class="op">=</span>p.sFRW,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>plt.gca(), color<span class="op">=</span>viridis[<span class="dv">2</span>], label<span class="op">=</span><span class="st">"middle-aged"</span>)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a><span class="co">## Oldest, sAGE = 1.0</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>abline_plot(intercept<span class="op">=</span>p.Intercept <span class="op">+</span> p[<span class="st">"sAGE"</span>], slope<span class="op">=</span>p.sFRW <span class="op">+</span> p[<span class="st">"sFRW:sAGE"</span>],</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>plt.gca(), color<span class="op">=</span>viridis[<span class="dv">4</span>], label<span class="op">=</span><span class="st">"oldest"</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>plt.legend()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="project_regression-analysis_files/figure-html/cell-9-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="593" height="429"></p>
</figure>
</div>
</div>
</div>
<p>How does the dependence of blood pressure on weight change as a person gets older? <strong><em>This question can be formally answered by taking the second-order mixed partial derivative of this regression function:</em></strong></p>
<div class="answers">
<p><span class="math display">\[
\widehat{SBP} = 150.5439 + ... + 16.6450⋅sFRW + 10.2189⋅sAGE - 2.0866(sFRW⋅sAGE) + ...
\]</span> The first partial derivative, change in SBP with respect to change in sFRW, is what the question means with the dependence of blood pressure on weight change. <span class="math display">\[
\frac{∂\widehat{SBP}}{∂sFRW} = 16.6450 - 2.0866⋅sAGE
\]</span> The second partial derivative, meanwhile, is the change in the dependence of blood pressure on weight change as age changes. <span class="math display">\[
\frac{∂\widehat{SBP}}{∂sFRW}\frac{∂}{∂sAGE} = - 2.0866
\]</span> The negative sign indicates the decreasing dependence of blood pressure on weight change decreases as a person gets older. This property is also shown in the illustration earlier. The slope of the line gets flatter and flatter from the youngest to the oldest age group of women. Although dampened, given the negative coefficient of the interaction <code>SEX</code>⋅<code>sAGe</code>, this property applies to the men as well.</p>
</div>
<section id="even-more-accurate-model" class="level3">
<h3 class="anchored" data-anchor-id="even-more-accurate-model">Even more accurate model</h3>
<p>Include the background variable <code>sCIG</code> from the data and its interactions. Visualize the model for systolic blood pressure as the function of the most important explanatory variable. Visualize separate lines for the small (-1.0), average (0.0), and large (1.0) values of <code>sCHOL</code>. Other variables can be assumed to be at their mean value.</p>
<div id="1c6d66c1" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 8</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.ols(<span class="st">'SBP ~ SEX + SEX:sFRW + SEX:sCHOL + SEX:sAGE + SEX:sCIG + sFRW + sFRW:sCHOL + sFRW:sAGE + sFRW:sCIG + sCHOL </span><span class="ch">\</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">              + sCHOL:sAGE + sCHOL:sCIG + sAGE + sAGE:sCIG + sCIG'</span>, </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>              data<span class="op">=</span>fram).fit()</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary())</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining colors based on viridis color map (yellow - violet)</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># I had to redefine it for each block to work with the test.</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>viridis <span class="op">=</span> {</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>: <span class="st">"#fde725"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>: <span class="st">"#addc30"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>: <span class="st">"#5ec962"</span>,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="dv">3</span>: <span class="st">"#28ae80"</span>,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="dv">4</span>: <span class="st">"#21918c"</span>,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="dv">5</span>: <span class="st">"#2c728e"</span>,</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="dv">6</span>: <span class="st">"#3b528b"</span>,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    <span class="dv">7</span>: <span class="st">"#472d7b"</span>,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>    <span class="dv">8</span>: <span class="st">"#440154"</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> fit.params</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>fram[fram.SEX<span class="op">==</span><span class="st">"female"</span>].plot.scatter(<span class="st">"sFRW"</span>, <span class="st">"SBP"</span>, c<span class="op">=</span>viridis[<span class="dv">8</span>])</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Small sCHOL = -1.0</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>abline_plot(intercept<span class="op">=</span>p.Intercept <span class="op">-</span> p[<span class="st">"sCHOL"</span>], slope<span class="op">=</span>p.sFRW <span class="op">-</span> p[<span class="st">"sFRW:sCHOL"</span>],</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>plt.gca(), color<span class="op">=</span>viridis[<span class="dv">0</span>], label<span class="op">=</span><span class="st">"small"</span>)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Average sCHOL = 0.0</span></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>abline_plot(intercept<span class="op">=</span>p.Intercept, slope<span class="op">=</span>p.sFRW,</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>plt.gca(), color<span class="op">=</span>viridis[<span class="dv">2</span>], label<span class="op">=</span><span class="st">"average"</span>)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Large sCHOL = 1.0</span></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>abline_plot(intercept<span class="op">=</span>p.Intercept <span class="op">+</span> p[<span class="st">"sCHOL"</span>], slope<span class="op">=</span>p.sFRW <span class="op">+</span> p[<span class="st">"sFRW:sCHOL"</span>],</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>plt.gca(), color<span class="op">=</span>viridis[<span class="dv">4</span>], label<span class="op">=</span><span class="st">"large"</span>)</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>plt.legend()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    SBP   R-squared:                       0.152
Model:                            OLS   Adj. R-squared:                  0.143
Method:                 Least Squares   F-statistic:                     16.50
Date:                Thu, 20 Jun 2024   Prob (F-statistic):           2.99e-40
Time:                        23:33:56   Log-Likelihood:                -6508.6
No. Observations:                1394   AIC:                         1.305e+04
Df Residuals:                    1378   BIC:                         1.313e+04
Df Model:                          15                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P&gt;|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept           151.3182      1.160    130.456      0.000     149.043     153.594
SEX[T.male]          -5.3834      1.598     -3.368      0.001      -8.519      -2.248
sFRW                 17.6415      1.866      9.455      0.000      13.981      21.302
SEX[T.male]:sFRW     -0.1140      3.441     -0.033      0.974      -6.865       6.637
sCHOL                 3.2957      1.965      1.677      0.094      -0.559       7.151
SEX[T.male]:sCHOL     1.4369      3.142      0.457      0.648      -4.727       7.600
sAGE                 10.3615      2.119      4.890      0.000       6.205      14.518
SEX[T.male]:sAGE     -4.4248      3.179     -1.392      0.164     -10.661       1.811
sCIG                  3.7733      3.106      1.215      0.225      -2.319       9.865
SEX[T.male]:sCIG     -3.9094      3.599     -1.086      0.278     -10.970       3.151
sFRW:sCHOL            4.8912      2.735      1.788      0.074      -0.475      10.257
sFRW:sAGE            -1.8501      2.848     -0.650      0.516      -7.437       3.737
sFRW:sCIG             3.6765      3.373      1.090      0.276      -2.941      10.294
sCHOL:sAGE           -4.8509      3.091     -1.569      0.117     -10.914       1.212
sCHOL:sCIG           -1.6344      3.368     -0.485      0.628      -8.242       4.973
sAGE:sCIG            -0.3247      3.143     -0.103      0.918      -6.490       5.840
==============================================================================
Omnibus:                      303.518   Durbin-Watson:                   1.802
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              750.095
Skew:                           1.164   Prob(JB):                    1.32e-163
Kurtosis:                       5.738   Cond. No.                         7.93
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="project_regression-analysis_files/figure-html/cell-10-output-2.png" class="quarto-figure quarto-figure-center figure-img" width="593" height="429"></p>
</figure>
</div>
</div>
</div>
<p>How does the model and its accuracy look?</p>
<hr>
<div class="answers">
<p>For this question, we can compare the R-squared between the two models, but since we are simply adding new variables from the previous model, it is better to compare the adjusted R-squared. The usual R-squared cannot fall if we add another explanatory variable. In this instance, for their respective R-squared and adjusted R-squared, the original model has 151 and 144, and this extended model has 152 and 143. The addition of <code>sCIG</code> and its interactions was not able to improve the model’s adjusted R-squared and in fact, gives a lower value. Even looking at the usual R-squared, there is little difference made. Now, it is important to be careful in omitting variables in a model. If <code>sCIG</code> has an effect on <code>SBP</code> and is correlated with the other explanatory variables in the model, we should not omit it. In this case, this is likely the case by looking at the changes in the beta coefficients of the other explanatory variables between the two models (with and without <code>sCIG</code> and its interactions). However, the beta coefficients of <code>sCIG</code> and its interactions are not statistically significant at the 10% level. On the other hand, a cursory look at medical literature will show that there may be a correlation between smoking and <a href="https://doi.org/10.7860%2FJCDR%2F2012%2F5086.2663">systolic blood pressure</a> and smoking and other explanatory variables like <a href="https://doi.org/10.1186/s12889-020-09975-w">cholesterol level</a>. This is what I meant earlier by not relying solely on the value of the R-squared in model evaluation.</p>
</div>
</section>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic regression</h2>
<div id="502057b3" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> logistic(x):</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">1.0</span> <span class="op">/</span> (<span class="fl">1.0</span> <span class="op">+</span> np.exp(<span class="op">-</span>x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will continue predicting high blood pressure by taking in some continuous background variables, such as the age.</p>
<p>Recreate the model <code>HIGH_BP ~ sFRW + SEX + SEX:sFRW</code> presented in the introduction. Make sure, that you get the same results. Use name <code>fit</code> for the fitted model. Compute and store the error rate into variable <code>error_rate_orig</code>.</p>
<div id="03c6424f" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 9</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define HIGH_BP</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>fram[<span class="st">"HIGH_BP"</span>] <span class="op">=</span> (fram.SBP <span class="op">&gt;=</span> <span class="dv">140</span>) <span class="op">|</span> (fram.DBP <span class="op">&gt;=</span> <span class="dv">90</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>fram.HIGH_BP <span class="op">=</span> fram.HIGH_BP.astype(<span class="st">"int"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.glm(formula<span class="op">=</span><span class="st">"HIGH_BP ~ SEX + SEX:sFRW + sFRW"</span>, data<span class="op">=</span>fram, family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary())</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain the error rate</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>error_rate_orig <span class="op">=</span> np.mean(((fit.fittedvalues <span class="op">&lt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> fram.HIGH_BP) <span class="op">|</span> ((fit.fittedvalues <span class="op">&gt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> <span class="op">~</span>fram.HIGH_BP))</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"error rate: </span><span class="sc">{</span>error_rate_orig<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                HIGH_BP   No. Observations:                 1394
Model:                            GLM   Df Residuals:                     1390
Model Family:                Binomial   Df Model:                            3
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -856.87
Date:                Thu, 20 Jun 2024   Deviance:                       1713.7
Time:                        23:33:57   Pearson chi2:                 1.39e+03
No. Iterations:                     4   Pseudo R-squ. (CS):            0.06351
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.7631      0.082      9.266      0.000       0.602       0.925
SEX[T.male]         -0.1624      0.120     -1.350      0.177      -0.398       0.073
sFRW                 1.0738      0.176      6.095      0.000       0.728       1.419
SEX[T.male]:sFRW     0.2709      0.287      0.943      0.346      -0.292       0.834
====================================================================================
error rate: 0.35581061692969873</code></pre>
</div>
</div>
<p>Add the <code>sAGE</code> variable and its interactions. Check the prediction accuracy of the model and compare it to the previous model. Store the prediction accuracy to variable <code>error_rate</code>.</p>
<div id="b05a5526" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 10</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.glm(formula<span class="op">=</span><span class="st">"HIGH_BP ~ SEX + SEX:sAGE + SEX:sFRW + sAGE + sAGE:sFRW + sFRW"</span>, data<span class="op">=</span>fram, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>              family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary())</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>error_rate <span class="op">=</span> np.mean(((fit.fittedvalues <span class="op">&lt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> fram.HIGH_BP) <span class="op">|</span> ((fit.fittedvalues <span class="op">&gt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> <span class="op">~</span>fram.HIGH_BP))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"error rate: </span><span class="sc">{</span>error_rate<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                HIGH_BP   No. Observations:                 1394
Model:                            GLM   Df Residuals:                     1387
Model Family:                Binomial   Df Model:                            6
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -845.51
Date:                Thu, 20 Jun 2024   Deviance:                       1691.0
Time:                        23:33:57   Pearson chi2:                 1.39e+03
No. Iterations:                     4   Pseudo R-squ. (CS):            0.07865
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.8079      0.084      9.569      0.000       0.642       0.973
SEX[T.male]         -0.1983      0.121     -1.632      0.103      -0.436       0.040
sAGE                 0.6008      0.173      3.466      0.001       0.261       0.941
SEX[T.male]:sAGE    -0.5727      0.239     -2.392      0.017      -1.042      -0.103
sFRW                 1.0196      0.180      5.670      0.000       0.667       1.372
SEX[T.male]:sFRW     0.3754      0.289      1.297      0.195      -0.192       0.943
sAGE:sFRW           -0.7588      0.276     -2.750      0.006      -1.300      -0.218
====================================================================================
error rate: 0.3278335724533716</code></pre>
</div>
</div>
<p>Visualize the predicted probability of high blood pressure as the function of weight. Remember to use normalized values (<code>rescale</code>) also for those variables that are not included in the visualization, so that sensible values are used for them (data average). Draw two figures with altogether six curves: young, middle aged, and old women; and young, middle aged, and old men. Use <code>plt.subplots</code>. (Plotting works in similar fashion as in the introduction. The argument factors need, however, be changed as in the example about visualisation of continuous variable.)</p>
<div id="b9641dcb" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 11</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> logistic(x):</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">1.0</span> <span class="op">/</span> (<span class="fl">1.0</span> <span class="op">+</span> np.exp(<span class="op">-</span>x))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining colors based on viridis color map (yellow - violet)</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>viridis <span class="op">=</span> {</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>: <span class="st">"#fde725"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>: <span class="st">"#addc30"</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>: <span class="st">"#5ec962"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="dv">3</span>: <span class="st">"#28ae80"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="dv">4</span>: <span class="st">"#21918c"</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="dv">5</span>: <span class="st">"#2c728e"</span>,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    <span class="dv">6</span>: <span class="st">"#3b528b"</span>,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="dv">7</span>: <span class="st">"#472d7b"</span>,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="dv">8</span>: <span class="st">"#440154"</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> fit.params</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the figures</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="co">## Setup the plot</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>, subplot_kw<span class="op">=</span>{<span class="st">"xlabel"</span>: <span class="st">"Weight"</span>, <span class="st">"ylabel"</span>: <span class="st">"Pr(Has high BP)"</span>}, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span>))</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="co">## Women</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].scatter(fram.sFRW[fram.SEX<span class="op">==</span><span class="st">"female"</span>], fram.HIGH_BP[fram.SEX<span class="op">==</span><span class="st">"female"</span>], c<span class="op">=</span>viridis[<span class="dv">8</span>], marker<span class="op">=</span><span class="st">"d"</span>)</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>X<span class="op">=</span>np.linspace(<span class="op">-</span><span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">100</span>)</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a><span class="co">### Youngest</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(X, logistic(X<span class="op">*</span>(p.sFRW <span class="op">-</span> p[<span class="st">"sAGE:sFRW"</span>])  <span class="op">+</span> (p.Intercept <span class="op">-</span> p.sAGE)), color<span class="op">=</span>viridis[<span class="dv">0</span>], label<span class="op">=</span><span class="st">"youngest"</span>)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a><span class="co">### Middle-aged</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(X, logistic(X<span class="op">*</span>p.sFRW <span class="op">+</span> p.Intercept), color<span class="op">=</span>viridis[<span class="dv">2</span>], label<span class="op">=</span><span class="st">"middle-aged"</span>)</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="co">### Oldest</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(X, logistic(X<span class="op">*</span>(p.sFRW <span class="op">+</span> p[<span class="st">"sAGE:sFRW"</span>])  <span class="op">+</span> (p.Intercept <span class="op">+</span> p.sAGE)), color<span class="op">=</span>viridis[<span class="dv">4</span>], label<span class="op">=</span><span class="st">"oldest"</span>)</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"Women"</span>)</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].legend()</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="co">## Men</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].scatter(fram.sFRW[fram.SEX<span class="op">==</span><span class="st">"male"</span>], fram.HIGH_BP[fram.SEX<span class="op">==</span><span class="st">"male"</span>], c<span class="op">=</span>viridis[<span class="dv">8</span>], marker<span class="op">=</span><span class="st">"d"</span>)</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>X<span class="op">=</span>np.linspace(<span class="op">-</span><span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">100</span>)</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a><span class="co">### Youngest</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(X, logistic(X<span class="op">*</span>(p.sFRW <span class="op">+</span> p[<span class="st">"SEX[T.male]:sFRW"</span>] <span class="op">-</span> p[<span class="st">"sAGE:sFRW"</span>]) <span class="op">+</span> (p[<span class="st">"SEX[T.male]"</span>] <span class="op">+</span> p.Intercept <span class="op">-</span> p.sAGE <span class="op">-</span> </span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>    p[<span class="st">"SEX[T.male]:sAGE"</span>])), color<span class="op">=</span>viridis[<span class="dv">0</span>], label<span class="op">=</span><span class="st">"youngest"</span>)</span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a><span class="co">### Middle-aged</span></span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(X, logistic(X<span class="op">*</span>(p.sFRW <span class="op">+</span> p[<span class="st">"SEX[T.male]:sFRW"</span>]) <span class="op">+</span> (p[<span class="st">"SEX[T.male]"</span>] <span class="op">+</span> p.Intercept)), color<span class="op">=</span>viridis[<span class="dv">2</span>], </span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>    label<span class="op">=</span><span class="st">"middle-aged"</span>)</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a><span class="co">### Oldest</span></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(X, logistic(X<span class="op">*</span>(p.sFRW <span class="op">+</span> p[<span class="st">"SEX[T.male]:sFRW"</span>] <span class="op">+</span> p[<span class="st">"sAGE:sFRW"</span>]) <span class="op">+</span> (p[<span class="st">"SEX[T.male]"</span>] <span class="op">+</span> p.Intercept <span class="op">+</span> p.sAGE <span class="op">+</span> </span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>    p[<span class="st">"SEX[T.male]:sAGE"</span>])), color<span class="op">=</span>viridis[<span class="dv">4</span>], label<span class="op">=</span><span class="st">"oldest"</span>)</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"Men"</span>)</span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].legend()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="project_regression-analysis_files/figure-html/cell-14-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1110" height="523"></p>
</figure>
</div>
</div>
</div>
<p>How do the models with different ages and genders differ from each other?</p>
<hr>
<div class="answers">
<p>To answer this question, it would be helpful to go through the process of determining the relevant equation for each of the groups. I’ll focus on the input <code>x</code> on the <code>logistic</code> function we defined earlier.</p>
<p>For women, with <code>SEX</code> = 0, the other variables are dropped.<br>
<span class="math display">\[
\widehat{HIGH\_BP}_{women} = 0.8079 + 0.6008⋅sAGE + 1.0196⋅sFRW - 0.7588(sAGE⋅sFRW)
\]</span> For different age groups, we set <code>sAGE</code> equals to -1 for the youngest, 0 for the middle-aged, and 1 for the oldest age groups.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{HIGH\_BP}_{women, youngest} =&amp;~0.8079 - 0.6008 + 1.0196⋅sFRW + 0.7588⋅sFRW \\
\widehat{HIGH\_BP}_{women, middle-aged} =&amp;~0.8079 + 1.0196⋅sFRW \\
\widehat{HIGH\_BP}_{women, oldest} =&amp;~0.8079 + 0.6008 + 1.0196⋅sFRW - 0.7588⋅sFRW
\end{aligned}
\]</span></p>
<p>Finally, group the values with <code>sFRW</code>.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{HIGH\_BP}_{women, youngest} =&amp;~0.8079 - 0.6008 + (1.0196 + 0.7588)sFRW \\
\widehat{HIGH\_BP}_{women, middle-aged} =&amp;~0.8079 + 1.0196⋅sFRW \\
\widehat{HIGH\_BP}_{women, oldest} =&amp;~0.8079 + 0.6008⋅ + (1.0196 - 0.7588)sFRW
\end{aligned}
\]</span> For men, we set the <code>SEX</code> = 1 and go through a similar process.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{HIGH\_BP}_{men} = &amp;~0.8079 - 0.1983 + 0.6008⋅sAGE - 0.5727⋅sAGE~+ \\
&amp;~1.0196⋅sFRW + 0.3754sFRW - 0.7588(sAGE⋅sFRW)
\end{aligned}
\]</span> Then we set, the appropriate values for the <code>sAGE</code> for each age group.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{HIGH\_BP}_{men, youngest} = &amp;~0.8079 - 0.1983 - 0.6008 + 0.5727~+ \\
&amp;~1.0196⋅sFRW + 0.3754⋅sFRW + 0.7588⋅sFRW \\
\widehat{HIGH\_BP}_{men, middle-aged} = &amp;~0.8079 - 0.1983 + 1.0196⋅sFRW + 0.3754⋅sFRW \\
\widehat{HIGH\_BP}_{men, oldest} = &amp;~0.8079 - 0.1983 + 0.6008 - 0.5727~+ \\
&amp;~1.0196⋅sFRW + 0.3754⋅sFRW - 0.7588⋅sFRW
\end{aligned}
\]</span> Finally, group the values with <code>sFRW</code>.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{HIGH\_BP}_{men, youngest} =&amp;~0.8079 - 0.1983 - 0.6008 + 0.5727~+ \\
&amp;~(1.0196 + 0.3754 + 0.7588)sFRW \\
\widehat{HIGH\_BP}_{men, middle-aged} =&amp;~0.8079 - 0.1983 + (1.0196 + 0.3754)sFRW \\
\widehat{HIGH\_BP}_{men, oldest} =&amp;~0.8079 - 0.1983 + 0.6008 - 0.5727~+ \\
&amp;~(1.0196 + 0.3754 - 0.7588)sFRW
\end{aligned}
\]</span></p>
<p>The values multiplied by <code>sFRW</code> are multiplied to X in the code earlier and everything else is treated as a constant. In other regression equations where there are other variables with no given value (like <code>SEX</code> and <code>sAGE</code>), we set them to 0 and thus are dropped. The former gives us the slope of the line, and the latter shifts the line horizontally. A right shift decreases the odds for all values of <code>sFRW</code>. Note: These values are not yet transformed. Given this, we can now use this in conjunction with the graph to compare the different regression lines. Comparing men and women within the same age group, the intercept for men is lower given the negative coefficient of <code>SEX</code>. On the other hand, the slope is also steeper for men given the positive coefficient of the interaction of <code>SEX</code> and <code>sFRW</code>. As for the different age groups, the beta coefficient of the interaction of <code>sAGE</code> and <code>sFRW</code> is negative. Thus, for the youngest (<code>sAGE</code> = - 1) the slope is steeper, for the oldest (<code>sAGE</code> = 1) the slope is flatter, and the middle-aged is in between those. The coefficient of age is positive, so relative to the middle-aged line, it shifts the line to the right for the youngest and shifts it to the left for the oldest. For men, the effect of age is dampened given the negative sign of the coefficient in the interaction term <code>SEX⋅sAGE</code>: <span class="math inline">\((0.6008 - 0.5727⋅SEX)sAGE\)</span>.</p>
<p>Simply, in terms of sex, being male lowers the odds of having high blood pressure at a baseline. However, the positive relationship between having high blood pressure and a person’s weight is stronger for men. As for age, being older has increased odds of having high blood pressure, but this relationship is weaker for men. Furthermore, as age increases, the positive relationship between having high blood pressure and a person’s weight is weakened.</p>
</div>
<hr>
<p>Create here a helper function <code>train_test_split</code> that gets a DataFrame as parameter and return a pair of DataFrames: one for training and the second for testing. The function should get parameters in the following way:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>train_test_split(df, train_fraction<span class="op">=</span><span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The data should be split randomly to training and testing DataFrames so that <code>train_fraction</code> fraction of data should go into the training set. Use the <code>sample</code> method of the DataFrame.</p>
<div id="9c5f22ae" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 12</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_test_split(df, train_fraction<span class="op">=</span><span class="fl">0.8</span>):</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    train <span class="op">=</span> df.sample(frac<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    test <span class="op">=</span> df[<span class="op">~</span>df.index.isin(train.index)]</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> train, test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Check the prediction accuracy of your model using cross validation. Use 100-fold cross validation and training_fraction 0.8.</p>
<div id="9647abe4" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 13</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>error_model<span class="op">=</span>[]</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>error_null<span class="op">=</span>[]</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">100</span>):</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    train, test <span class="op">=</span> train_test_split(fram, train_fraction<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    fit <span class="op">=</span> smf.glm(formula<span class="op">=</span><span class="st">"HIGH_BP ~ SEX + SEX:sAGE + SEX:sFRW + sAGE + sAGE:sFRW + sFRW"</span>, data<span class="op">=</span>train, </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>              family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    pred <span class="op">=</span> fit.predict(test, transform<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    error_rate <span class="op">=</span> np.mean(((pred <span class="op">&lt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> (test.HIGH_BP<span class="op">==</span><span class="dv">1</span>)) <span class="op">|</span> ((pred <span class="op">&gt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> (test.HIGH_BP<span class="op">==</span><span class="dv">0</span>)))</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    error_model.append(error_rate)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    error_null.append((<span class="dv">1</span> <span class="op">-</span> test.HIGH_BP).mean())</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>pd.Series(error_model).mean(), pd.Series(error_null).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>(0.3311827956989247, 0.3488530465949821)</code></pre>
</div>
</div>
<section id="predicting-coronary-heart-disease" class="level3">
<h3 class="anchored" data-anchor-id="predicting-coronary-heart-disease">Predicting coronary heart disease</h3>
<p>Let us use again the same data to learn a model for the occurrence of coronary heart disease. We will use logistic regression to predict whether a patient <em>sometimes</em> shows symptoms of coronary heart disease. For this, add to the data a binary variable <code>hasCHD</code>, that describes the event (<code>CHD &gt; 0</code>). The binary variable <code>hasCHD</code> can get only two values: 0 or 1. As a sanity check, compute the mean of this variable, which tells the number of positive cases.</p>
<div id="c111c556" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 14</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>fram[<span class="st">"hasCHD"</span>] <span class="op">=</span> fram.CHD <span class="op">&gt;</span> <span class="dv">0</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>fram.hasCHD <span class="op">=</span> fram.hasCHD.astype(<span class="st">'int'</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fram.hasCHD.mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.22022955523672882</code></pre>
</div>
</div>
<p>Next, form a logistic regression model for variable <code>hasCHD</code> by using variables sCHOL, sCIG, and sFRW, and their interactions as explanatory variables. Store the fitted model to variable <code>fit</code>. Compute the prediction accuracy of the model, store it to variable <code>error_rate</code>.</p>
<div id="ecf03c6b" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 15</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.glm(formula<span class="op">=</span><span class="st">"hasCHD ~ sFRW + sFRW:sCHOL + sFRW:sCIG + sCHOL + sCHOL:sCIG + sCIG"</span>, data<span class="op">=</span>fram, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>              family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit.summary())</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain the error rate</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>error_rate <span class="op">=</span> np.mean(((fit.fittedvalues <span class="op">&lt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> fram.hasCHD) <span class="op">|</span> ((fit.fittedvalues <span class="op">&gt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> <span class="op">~</span>fram.hasCHD))</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(error_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                 hasCHD   No. Observations:                 1394
Model:                            GLM   Df Residuals:                     1387
Model Family:                Binomial   Df Model:                            6
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -721.19
Date:                Thu, 20 Jun 2024   Deviance:                       1442.4
Time:                        23:34:02   Pearson chi2:                 1.39e+03
No. Iterations:                     4   Pseudo R-squ. (CS):            0.01950
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.2888      0.067    -19.101      0.000      -1.421      -1.157
sFRW           0.4404      0.130      3.386      0.001       0.185       0.695
sFRW:sCHOL     0.1359      0.239      0.568      0.570      -0.333       0.604
sFRW:sCIG      0.1646      0.258      0.637      0.524      -0.342       0.671
sCHOL          0.3324      0.130      2.554      0.011       0.077       0.587
sCHOL:sCIG    -0.1022      0.273     -0.374      0.708      -0.637       0.433
sCIG           0.4613      0.126      3.666      0.000       0.215       0.708
==============================================================================
0.22022955523672882</code></pre>
</div>
</div>
<p>Visualize the model by using the most important explanator on the x axis. Visualize both the points (with <code>plt.scatter</code>) and the logistic curve (with <code>plt.plot</code>).</p>
<div id="e380ca36" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 16</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> logistic(x):</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">1.0</span> <span class="op">/</span> (<span class="fl">1.0</span> <span class="op">+</span> np.exp(<span class="op">-</span>x))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining colors based on viridis color map (yellow - violet)</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>viridis <span class="op">=</span> {</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>: <span class="st">"#fde725"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>: <span class="st">"#addc30"</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>: <span class="st">"#5ec962"</span>,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    <span class="dv">3</span>: <span class="st">"#28ae80"</span>,</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    <span class="dv">4</span>: <span class="st">"#21918c"</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    <span class="dv">5</span>: <span class="st">"#2c728e"</span>,</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    <span class="dv">6</span>: <span class="st">"#3b528b"</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    <span class="dv">7</span>: <span class="st">"#472d7b"</span>,</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="dv">8</span>: <span class="st">"#440154"</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>plt.scatter(fram.sCIG, fram.hasCHD, marker<span class="op">=</span><span class="st">"d"</span>, c<span class="op">=</span>viridis[<span class="dv">8</span>])</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>X<span class="op">=</span>np.linspace(<span class="op">-</span><span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">100</span>)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> fit.params</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>plt.plot(X, logistic(X<span class="op">*</span>p.sCIG <span class="op">+</span> p.Intercept), color<span class="op">=</span>viridis[<span class="dv">0</span>])</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Smoking"</span>)</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Pr(Has CHD)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>Text(0, 0.5, 'Pr(Has CHD)')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="project_regression-analysis_files/figure-html/cell-19-output-2.png" class="quarto-figure quarto-figure-center figure-img" width="589" height="429"></p>
</figure>
</div>
</div>
</div>
<p>Is the prediction accuracy of the model good or bad? Can we expect to have practical use of the model?</p>
<hr>
<div class="answers">
<p>It is harder to answer the questions above without other metrics. This section only calculated the in-sample error rate, which is not useful. We generally want the prediction for a sample with an unknown value for the y. For instance, with the previous section predicting the dependent variable <code>HIGH_BP</code>, I conducted a check of prediction accuracy with cross-validation for the test dataset based on the training dataset. This can be helpful, but even with this, this may not be sufficient. We placed equal weight on the two types of error: false positives and false negatives.</p>
<p>Below is the decomposition of the error rate:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> smf.glm(formula<span class="op">=</span><span class="st">"hasCHD ~ sFRW + sFRW:sCHOL + sFRW:sCIG + sCHOL + sCHOL:sCIG + sCIG"</span>, data<span class="op">=</span>fram, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>              family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>false_negative <span class="op">=</span> np.<span class="bu">sum</span>((fit.fittedvalues <span class="op">&lt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> (fram[<span class="st">"hasCHD"</span>] <span class="op">==</span> <span class="dv">1</span>))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>actual_positive <span class="op">=</span> np.<span class="bu">sum</span>(fram[<span class="st">"hasCHD"</span>] <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>false_positive <span class="op">=</span> np.<span class="bu">sum</span>((fit.fittedvalues <span class="op">&gt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> (fram[<span class="st">"hasCHD"</span>] <span class="op">==</span> <span class="dv">0</span>))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>actual_negative <span class="op">=</span> np.<span class="bu">sum</span>(fram[<span class="st">"hasCHD"</span>] <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>error_rate_falseneg <span class="op">=</span> false_negative <span class="op">/</span> actual_positive</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>error_rate_falsepos <span class="op">=</span> false_positive <span class="op">/</span> actual_negative</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"false negative rate: </span><span class="sc">{</span>error_rate_falseneg<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>false_negative<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>actual_positive<span class="sc">}</span><span class="ss">), </span><span class="ch">\</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="ss">false positive rate: </span><span class="sc">{</span>error_rate_falsepos<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>false_positive<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>actual_negative<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># false negative rate: 0.9869706840390879 (303/307), false positive rate: 0.0036798528058877645 (4/1087)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>In the case of diagnosing coronary heart disease, false negatives can be more detrimental to the patient. This means they are not receiving the proper intervention when they should. False positives can have costs too, but they are usually only financial. In any case, the diagnosis eventually gets sorted out with further testing, which the positive prediction prompts. Barring all that, the error rate for the model is no better than the error rate by simply guessing the most common outcome, having no coronary heart disease. Therefore, this model is not likely to have practical use.</p>
</div>
<hr>
<p>If a person has cholestherol 200, smokes 17 cigarets per day, and has weight 100, then what is the probability that he/she sometimes shows signs of coronal hear disease? Note that the model expects normalized values. Store the normalized values to dictionary called <code>point</code>. Store the probability in variable <code>predicted</code>.</p>
<div id="74bab48d" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exercise 17</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Put your solution here!</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> <span class="st">"FRW CHOL CIG"</span>.split()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>vals <span class="op">=</span> [<span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">17</span>]</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># This is used in my first solution, but this function is not being recognized by the test.</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># def normalize(df, col, val): </span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co">#     s = df[col]</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">#     center = s.mean()</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co">#     normal = 2*s.std()</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">#     return (val-center)/normal</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># point = dict(zip(["s"+x for x in cols], [normalize(fram, x, y) for x, y in zip(cols, vals)]))</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    point <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>([<span class="st">"s"</span><span class="op">+</span>x <span class="cf">for</span> x <span class="kw">in</span> cols], <span class="bu">list</span>(<span class="bu">map</span>(<span class="kw">lambda</span> x, y: (x<span class="op">-</span>fram[y].mean())<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>fram[y].std()), vals, cols))))</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">NameError</span>: <span class="co"># The test do not recognize the `fram` variable, so this is the alternative.</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    point <span class="op">=</span> {<span class="st">'sFRW'</span>: <span class="op">-</span><span class="fl">0.1511094123560532</span>, <span class="st">'sCHOL'</span>: <span class="op">-</span><span class="fl">0.37410417825308084</span>, <span class="st">'sCIG'</span>: <span class="fl">0.3871927538102119</span>}</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(point)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>predicted <span class="op">=</span> fit.predict(point)[<span class="dv">0</span>]</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'sFRW': -0.1511094123560532, 'sCHOL': -0.37410417825308084, 'sCIG': 0.3871927538102119}
0.21616166025041</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>